### ISSUE TITLE
Change tests to use separate configurations for `cargo test`

### ISSUE THREAD

**Issue by StoneDot** [awslabs/dynein#199]
Currently, the `cargo test` command uses the default configuration directory, `$HOME/.dynein`. This means that our configuration is replaced after `cargo test`. This is not good from the perspective of the developer's experience. We want to fix this behavior by using individual configurations for tests.

**Comment by ryota-sakamoto** [comment]
We can use `DYNEIN_CONFIG_DIR` to load configuration on other directory instead of default directory.

https://github.com/awslabs/dynein/blob/748c68ec683e7e7798ec9b1f2130a040589d15dc/src/app.rs#L649

The env is already used on the specific test so we can expand it to all of the tests.

https://github.com/awslabs/dynein/blob/748c68ec683e7e7798ec9b1f2130a040589d15dc/tests/auxiliary.rs#L47
